language: c
sudo: false

env:
    matrix:
        - CONDA_PY=3.4
        - CONDA_PY=3.5

branches:
  only:
    - master

install:
    - source devtools/travis-ci/install_miniconda.sh
    - conda config --add channels omnia
    - conda config --add channels astropy
    - conda install -yq python-coveralls

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    - conda build --quiet devtools/conda-recipe
    - devtools/travis-ci/build_docs.sh

after_success:
  - cp $HOME/miniconda3/conda-bld/test-tmp_dir/.coverage .
  - coveralls
