language: c
sudo: false
env:
  matrix:
  - CONDA_PY=3.4
  - CONDA_PY=3.5
branches:
  only:
  - master
install:
- source devtools/travis-ci/install_miniconda.sh
- conda config --add channels omnia
- conda config --add channels astropy
- conda install -yq python-coveralls
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- conda build --quiet devtools/conda-recipe
- devtools/travis-ci/build_docs.sh
after_success:
- cp $HOME/miniconda3/conda-bld/test-tmp_dir/.coverage .
- coveralls
deploy:
  - provider: s3
    bucket: msmbuilder.org
    upload-dir: msmexplorer
    skip_cleanup: true
    local_dir: docs/_deploy/
    on:
      branch: master
      condition: "$CONDA_PY = 3.5"
    access_key_id:
      secure: "o/yscio6VtpgJv2hpytI2ZZyMb4jR91AFCEGvrQFWxZpzYEqH9r2iGyTA9ex0ohcFC2/a8B8F8tvtQ/KxFsHkwBY78SR060v053ItL0q1oY11m04M+iS4VXyCigCUN8RDK7Btz7v/pATTxMAnG27eou7PmKZ+n70FxJ16MI2TCnqv6g7Fix3saj0WvnPxvge8vbF8jh6UIai0hGiWbzy3r3zYewE7diI9CN74yfFhZ5SGYNMDg3IXMD3yMAVBqXALmTM6tTrmkrkxTnQOKsUz+kgngXJz4qZi2U0IkWXYyAz6/4Ej4dpwDfyFonvw9xSMxptavAm3/qB1V7Bnqzka1+sqMvxXFzNA01QCTk83zwVWutev5NwTmORm3xmx9AaTyCBgNWPZYMzpdqsxVieQn+I3Odc/wJdra4WN+f/K6ZI7ScpnqHPDZFUSmxjSBG1f1LVq4AFMo++DfaJH/3yqaI75FRsGk1S0vnwa0t1ixM905+8UmQn0ZehzBhWL8rNE9zNa/Zaw/eOUpxub/99/5lZV6EAlcACnhJuKky6Bci00qrK6APW3sXjheLDA3iLX2Exdy0OdBIM7lEBSXT69VSU1sY2KmyACGkAJSsBELHMp3kv+u7xkR3miM9dWToTCUaYcLUuIctcDJUzBIS2vMIwPrt0bqwii3t0VaddggM="
    secret_access_key:
      secure: "a4QeiPzjCGTKcJRysl4ct5AXaZwxPzxgfGwzyp/TO2KH/OoOn6VsSkDbFe7OnJGgTEciBsbKaJtwYTvAvMUbcS7IzJsD4bdcLdpASyFw0qJFJUIdbjlPDs0O3snE95kDp8zIxFjewJHZued6NxlWXW8snLgfju+POKEFJNM40YqL7G3wWLGkRGqHvYpj/7qvXgQniPCmFseko7qn+rn3ozoQdkFpPrK5HPQgPKUqDSA+alcVRaEKnD7WcaNa8InzqKyFxDf/wVZDHytNClQLX/O2HFTAy07vmzOPY+dDOfEoyiU2aeABGm2fTY63tE9s2bVx+UKHA2fZmMDPl/U/lv+BGlwRlDB84OhLCUePoz6aOKmvY+GYe/m++x2G/0ygLaUwHrO5gZjIbPLjTj2LdiHntGXCwAPEHPVxOG37S8swW5A9W1kUuk51x0/gsPUsXpXde9GUFAZ/nqtfoiGkds4fYfmgsVja2Nzt+Kn5QHmo27aaBQOmgTNjncilRk4tFfME9rqw/QgXwoSq1tYZbzjQZ23nhpI2kxuaDYURjwYv0dBhfBbURY/aAJZkkz+DuAi+g2GMnizI7Hm9+ocSvIlFXePO96qahbo/60BzfwdO5niw3p62IrcJhGkT5h+e1DzshRt+C7mWWyt7YNo5Idh8MncAKwFVNsgwlo3z0Fo="
