language: c
sudo: false
os:
  - osx
  - linux
env:
  matrix:
  - CONDA_PY=3.4
  - CONDA_PY=3.5
  - CONDA_PY=3.6

branches:
  only:
  - master

addons:
  apt:
    packages:
      - xvfb

install:
- source devtools/travis-ci/install_miniconda.sh
- conda config --add channels omnia

before_script:
- |
  if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
    export DISPLAY=:99.0
    sh -e /etc/init.d/xvfb start
  fi

script:
- conda build --quiet devtools/conda-recipe
  && devtools/travis-ci/build_docs.sh

after_success:
- cp $HOME/miniconda3/conda-bld/test-tmp_dir/.coverage .
- coveralls

deploy:
  - provider: s3
    bucket: msmbuilder.org
    upload-dir: msmexplorer
    skip_cleanup: true
    local-dir: docs/_deploy/
    on:
      branch: master
      condition: "$CONDA_PY = 3.5 && $TRAVIS_OS_NAME = 'linux'"
    region: us-east-1
    detect_encoding: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
