language: c
sudo: false
env:
  matrix:
  - CONDA_PY=3.4
  - CONDA_PY=3.5
branches:
  only:
  - master
install:
- source devtools/travis-ci/install_miniconda.sh
- conda config --add channels omnia
- conda config --add channels astropy
- conda install -yq python-coveralls
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- conda build --quiet devtools/conda-recipe
- devtools/travis-ci/build_docs.sh
after_success:
- cp $HOME/miniconda3/conda-bld/test-tmp_dir/.coverage .
- coveralls
deploy:
  - provider: s3
    access_key_id:
      secure: "ppBTSkWPQEFSzqJeFtNdAgqvcFeIiNvHDxvUcqqoHtqTcWpILElk5v976ba4MrdxKtiIhS4PfQg3+INwrmlV2bzPc4hPHt3eXoxEBy/jmht75txGHskeF+kRh3MIPxve/xZ4059lGiHy2bLvbU6b0yrWdHi57+5Hicl3DCV6raoxaDyFkY4WcH5aoDKPeUeAhVkBSAn2cIXFEdIfaVGqvRYy4x27H+4mq1JFzSwcQM9KMxoAmt93MjprRaMMMcoffKTqUSsoghwvRvABE67/WkvmyVH2GQg7AfzdMdYon36zBwA9yMBO+mOOsc/bw2CKzOyHBuok2vkoCr30TC6GWW7UQMiMfIA7AEhg+GWrTzt+oNvqkw4uaMtCNIumuJAdmpzaYy5GY4nFThurZZ+S5KCu7lb4uW19MbTUbFRtccR436wzODthVPEScIgXHRFpKv+jSSNh0saUctw7GZhm/U38TtI5IK1goe4lkVnzUVii0ftXvBS6NMxaf4n2wWbpXcGjRugg8q7sDfIKvJobMuCeO06m2cg3MxIuPFtJQxI45TToMD+P3r6fRg2vPb2EJoD0G4GWe5melCLyJkm3/J1b2jvynA2dW+ROtiANJs4QGnUtC6dc2He+NRLA47I5/dCSu7HXRJZIfvK3zKn2Gm4XBNXwXLSisfck8kR4WqM="
    secret_access_key:
      secure: "J3IaMOPayTVzv/Z2CIII48vSMJZpTvnzK1pR1zjFnlQKOFekW6gRjvqtLPYij7qYKem+6zklLXVoRxASMxcXtcOhnM2K68Kn+GoW6dNFAqkLxjPE7iyM7TAbrXxBNQjGjPsern+kZFCg62uKTkKpMdUSqpIrlObKzx3VxQADWZqkQqTrMK20n+gMzvyk5u8hDhLQrIgH1xnosh0kSgyydIk5MsobSnB9ecSJQvryAgZATcadqziCrinbdWSqDrDSp9LyhNoev91D9qRlkBmtuLBoLzMhDCLVMe34bY3Sb3vEdmyeNBqqQFog8pjWOZotozVrAcD9SEFZmNABR5E0f9hy/1cxRbRcBGoiP+46UinmY26pXqwpt+Ixt1k9UKrE4S47FS4C4I0jqPvJCPcdvz06Qvit80nwVytnrJ3zusu29WJZYi0xgF7c2blIlr1w/PteRx13mmf+9vRLwvLjhTC85UwVVjBHfKAuP61L+4DIID4lDy2Ytvw3BItIR1bOU2P1JWvSA31Qx/2wdXnKF9U3Az7vJ4dAQ7PTHY/jqZq8zvdIvReuh9knHwpw0lg3vql+pFrkjTIULQSS67nttzyLuAEB+qTCtFS25cga2wb0Ipp1D2ksYqvUwO18vW4xmBM+0S74o8lDb2bGxanZpq7nmnS/XAMQ4ip7CK7OeLA="
    bucket: "msmbuilder.org"
    upload-dir: msmexplorer
    skip_cleanup: true
    local-dir: docs/_deploy/
    on:
      branch: master
      condition: "$CONDA_PY = 3.5"
    region: us-east-1
    detect_encoding: true
