language: c
sudo: false
env:
  matrix:
  - CONDA_PY=3.4
  - CONDA_PY=3.5
branches:
  only:
  - master
install:
- source devtools/travis-ci/install_miniconda.sh
- conda config --add channels omnia
- conda config --add channels astropy
- conda install -yq python-coveralls
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- conda build --quiet devtools/conda-recipe
- devtools/travis-ci/build_docs.sh
after_success:
- cp $HOME/miniconda3/conda-bld/test-tmp_dir/.coverage .
- coveralls
deploy:
  - provider: s3
    bucket: msmbuilder.org
    upload-dir: msmexplorer
    skip_cleanup: true
    local-dir: docs/_deploy/
    on:
      branch: master
      condition: "$CONDA_PY = 3.5"
    region: us-east-1
    detect_encoding: true
    access_key_id:
      secure: Ew2vaBu42sQYv4m8ushegjhTEDJm+QDsvKaWtuGo4HgTON5vMC+jGFu/gj+C+ej4SG8cmlw/LKdQ95QG37IhSk3F7P2cm9hUKIpFpH9MEXD5T3HmJlVe9Gp9It5ps4n2NJLWxX4OIgLHbyq3+mKDj7VMJURMb5PhnbtpOksNaZqb9Kipi8B1XzJe9Wa+B6L/iiaW0T7qC1JRKMrl+5QKLCnXk3iEroyhDCKMNub4nigFTvV8yLZElZooD99c4Bbj3FTL45FJXNnPplgYHAJUc+WeO80RR3MPhpq6mOmgeYd1Tu+G8eUdn6vCAR3DrrqTBpLBRh5tj+L290M4yruRPsqNI1v24xyzN9NFGHKB2dp/+q31GwN/+B8HKLhtCp6sZX3iMk9Wt3Kekcp32fnnnuQk0xnOX2Er9NuafqbQZGkZf6w1dqz8FKtKKIx3MQxmwMcjqzC0duxwDHUpqLlqY/NaPXJcE+kmIWINZS+5rEm6ZfJ2KiZBiWOCU9LnUw1s5xlxphuHCMsKLQ4LUktEs28FmTqcCPwsa6qZbDmH4Ju7GolaWgUVnFx9j3KVl/o3iA0wvsKoCXgmq218bPW95z9euA6rg1JbgETI5CPAdvISk7jdO7boqa996FkGK+7hWGL45CHZvpZikbJ7l0zlgsLqwlVFbNVc7jwG90RtAG4=
    secret_access_key:
      secure: YTBi71xzd1YW5CSCViVC7EvKrZoLDyuR0vrT92vnnMD7M0eb4lMRR3PvyLUYCnAT77soxKHQ7IH+t+XNi2GKFOYNrLon+Xr4fidZlbAdebuGF+kD96+9MLsCrin4ThJ6HdB/50BKq0xEcIz1Ue72DhTvuJv4U46qTPhLQKVLOqgKQewPzLRLggJYL7G8F2Ti1AWq1iV5rXRXCWoj//r2TtUdGzhVZS07gCoaKu8zFbC4ih+g+5TCnSsiLElOG7mh4l0kRgu8N+lbDKUMUVkZtDo7C7vFtsf2IfOleDP5ZWRbWb1PxpshOOg/NFr1aQ7vs2GteeovifZiEhcZUWtNufc1vk04IGExP9dQdZbYcTxk6tYAP7qvsYJVZrVEh6IbQvZOnRqs+LwieLoPCoMdblMQk5J0pGcYGHocw7U7pkpoDpMacMxVVnnZutaj31Mg8JUz7Cyjd8v7Y+AGtPxRPYyOcqKnI1XPy643tVtDzLGd8TGizjhsiwgcDt9W6F0+0P/Lci+1YfaNGI3OKjo4l2OaVNYgKlsByPQnN5wPUqy/6lW5pYL11coJ0yGtHSKHtegcbMP8HcR1QEjuMbj+2dB4YXhDYgAiWYFOumZ3Kyn79Ti35VpSCaoDCkNajSHKWPj8eZF2AFri0qKVZs+eCZAdkWFZXcqlHSCpxtP8XqM=
