package:
  name: msmexplorer
  version: "0.1.0.dev0"

source:
  path: ../../

build:

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pandas
    - msmbuilder
    - mdtraj
    - nglview
    - matplotlib
    - networkx

test:

  requires:
    - nose
    - nose-timer
    - numpy
    - pandas
    - msmbuilder
    - mdtraj
    - nglview
    - matplotlib
    - networkx

  imports:
    - msmexplorer

  commands:
    - nosetests -v msmexplorer --with-timer

about:
  home: https://github.com/msmexplorer/msmexplorer
  license: MIT
  summary: 'Visualizations for statistical models of biomolecular dynamics'
