package:
  name: msmexplorer
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy

  run:
    - python
    - numpy
    - pandas
    - msmbuilder
    - mdtraj
    - nglview
    - matplotlib
    - seaborn
    - statsmodels
    - networkx
    - corner
    - six

test:

  requires:
    - nose
    - nose-timer
    - python-coveralls

  imports:
    - msmexplorer
    - msmexplorer.tests
    - matplotlib

  commands:
    - nosetests -v msmexplorer --with-timer --with-coverage  --cover-package=msmexplorer

about:
  home: https://github.com/msmexplorer/msmexplorer
  license: MIT
  summary: 'Visualizations for statistical models of biomolecular dynamics'

# vim: ts=2 sw=2 et
